language: php

sudo: required

services:
    - docker

cache:
    directories:
        - $HOME/.composer/cache

branches:
    only:
        - master

php:
    - 7.1
    - 7.2

matrix:
    fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer install --optimize-autoloader --no-interaction --prefer-source

script:
    - make solr_start
    - make database
    - make tests
    - make rusty
